language: php
php:
  - 5.3
  - 5.4

before_script:
 - composer selfupdate --quiet
 - composer install --dev
 - vendor/phpunit/phpunit/composer/bin/phpunit

notifications:
  irc: "irc.freenode.org#garyj"
  email: false